# Generated by Django 2.1.5 on 2019-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=25)),
                ('pizza_type', models.CharField(max_length=25)),
                ('pizza_description', models.CharField(max_length=200)),
                ('pizza_price', models.IntegerField(default=0)),
            ],
        ),
    ]
