# Generated by Django 2.1.5 on 2019-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='pizza',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
