# Generated by Django 2.2 on 2019-04-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190224_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['pizza_price']},
        ),
    ]
