# Generated by Django 2.2.2 on 2019-07-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190422_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['topping_price']},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('total_items', models.IntegerField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza')),
            ],
        ),
    ]
