# Generated by Django 2.2.2 on 2019-07-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190705_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pizza',
        ),
    ]
