# Generated by Django 2.2.5 on 2019-09-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190804_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
